"""Git PR generation helpers for kube-saver.

Generates a local ".kube-saver/" directory with a summary and
patch files the user can review and apply manually.  No network
calls or external service dependencies.
"""

from __future__ import annotations

import json as json_mod
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from kube_saver.models.core import Recommendation


@dataclass
class PullRequestPlan:
    """Dry-run or executable PR creation plan.

    Attributes:
        branch_name: Suggested git branch name.
        title: Suggested PR / commit title.
        body: Markdown summary of what changed.
        files: Mapping of relative filename \u2192 content to write.
        dry_run: Always ``True`` \u2014 kube-saver never opens PRs itself.
    """

    branch_name: str
    title: str
    body: str
    files: dict[str, str] = field(default_factory=dict)
    dry_run: bool = True


def generate_pr_plan(
    recommendations: list[Recommendation],
    *,
    branch_prefix: str = "kube-saver",
) -> PullRequestPlan:
    """Generate a local PR plan from *recommendations*.

    No network calls are made.  The returned plan can be persisted
    with ``apply_plan_locally``.
    """
    branch_name = f"{branch_prefix}/optimize-resources"
    title = "Apply kube-saver resource recommendations"
    lines: list[str] = [
        "## Summary\n",
        f"- Recommendations: {len(recommendations)}\n",
        "## Before / After\n",
    ]
    for rec in recommendations:
        lines.append(
            f"- **{rec.target_namespace}/{rec.target_kind}/{rec.target_name}**"
            f" `{rec.resource_type}`: {rec.current_value} \u2192 {rec.suggested_value}"
        )
    lines.extend([
        "\n## Safety\n",
        "- All suggestions are derived from actual resource waste analysis.",
        "- Review carefully before applying to production.",
    ])
    body = "\n".join(lines)

    # Build kubectl patch commands (one per workload)
    patches: list[str] = ["#!/usr/bin/env bash", "# kube-saver generated patch commands", ""]
    by_workload: dict[tuple[str, str, str], list[Recommendation]] = {}
    for rec in recommendations:
        key = (rec.target_namespace, rec.target_kind, rec.target_name)
        by_workload.setdefault(key, []).append(rec)
    for (ns, kind, name), recs in by_workload.items():
        patches.append(f"# {ns}/{kind}/{name}")
        patches.append(f"kubectl patch {kind.lower()} {name} -n {ns} \\")
        # Build JSON merge patch
        container_patch: dict[str, object] = {}
        for rec in recs:
            res = container_patch.setdefault("resources", {})
            if not isinstance(res, dict):
                res = {}
                container_patch["resources"] = res
            if rec.resource_type == "cpu-request":
                res.setdefault("requests", {})["cpu"] = rec.suggested_value
            elif rec.resource_type == "memory-request":
                res.setdefault("requests", {})["memory"] = rec.suggested_value
            elif rec.resource_type == "cpu-limit":
                res.setdefault("limits", {})["cpu"] = rec.suggested_value
            elif rec.resource_type == "memory-limit":
                res.setdefault("limits", {})["memory"] = rec.suggested_value
        patch_json = json_mod.dumps(
            {"spec": {"template": {"spec": {"containers": [container_patch]}}}},
            separators=(",", ":"),
        )
        patches.append(f"  --type=merge -p \'{patch_json}\'")
        patches.append("")

    patch_text = "\n".join(patches)
    readme = (
        "# kube-saver recommendations\n\n"
        "Generated by kube-saver.\n\n"
        "## Files\n\n"
        "- `summary.md` \u2014 human-readable summary of all recommendations.\n"
        "- `apply-patches.sh` \u2014 kubectl patch commands (review before running).\n"
        "- `review.txt` \u2014 plain-text review notes.\n\n"
        "## How to apply\n\n"
        "1. Review `summary.md`.\n"
        "2. Review `apply-patches.sh`.\n"
        "3. Run: `bash apply-patches.sh` (in a staging cluster first!).\n"
    )

    files: dict[str, str] = {
        "summary.md": body,
        "apply-patches.sh": patch_text,
        "README.md": readme,
        "review.txt": (
            f"kube-saver PR plan \u2014 {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            f"Suggested branch: {branch_name}\n\n"
            f"{body}\n"
        ),
    }
    return PullRequestPlan(
        branch_name=branch_name,
        title=title,
        body=body,
        files=files,
        dry_run=True,
    )


def apply_plan_locally(
    plan: PullRequestPlan,
    output_dir: str | Path = ".kube-saver",
) -> Path:
    """Write all plan files to *output_dir* and return the path.

    Creates *output_dir* if it doesn't exist.  Existing files with the
    same name are overwritten (use ``output_dir=".kube-saver/<timestamp>"``
    for unique runs).
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    for fname, content in plan.files.items():
        p = out / fname
        p.write_text(content, encoding="utf-8")
    return out


__all__ = ["PullRequestPlan", "generate_pr_plan", "apply_plan_locally"]
